export const products = [
  {
    cid:1,
    ccid:1,
    id: 1,
    
    name: 'iPhone XR',
    price: 799,
    description: 'A large phone with one of the best screens',
    likes: 555,
    rating:5,
    image:'https://m.media-amazon.com/images/I/51n24DedexL._FMwebp__.jpg',
  },
  { cid:1,
    ccid:1,
    id: 2,
    name: 'iPhone 12 Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    likes: 5555,
    rating:7,
    image:'https://m.media-amazon.com/images/I/71uuDYxn3XL._FMwebp__.jpg',
  },
  { cid:1,
    ccid:1,
    id: 3,
    name: 'Xiaomi Redmi Note 9S',
    price: 299,
    description: '',
    likes: 25255,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/61UnStT8VfL._AC_SL1000_.jpg',
  },
  { cid:1,
    ccid:1,
    id: 4,
    name: 'Samsung Galaxy S20 FE 5G',
    price: 299,
    description: '',
    likes: 1112,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/71z2dc%2BXnrL._AC_SL1500_.jpg',
  },
  { cid:1,
    ccid:1,
    id: 5,
    name: 'Xiaomi Redmi Note 8',
    price: 299,
    description: '',
    likes: 1112,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/51RLwrAQglL._AC_SL1000_.jpg',
  },
  { 
    cid:2,
    ccid:2,
    id: 6,
    name: 'HP Chromebook 14',
    price: 299,
    description: '',
    likes: 1112,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/91XR%2B02AJBL._AC_SL1500_.jpg',
  },
  { 
    cid:2,
    ccid:2,
    id: 7,
    name: 'Lenovo IdeaCentre AIO 3, 24"',
    price: 299,
    description: 'Accelerate everything you do with the IdeaCentre AIO 3. Powered by AMD Ryzen 5 4500U <br> mobile processors with Radeon graphics, this all-in-one computer makes multitasking a breeze',
    likes: 11222,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/81eRAX3sB6L._AC_SL1500_.jpg',
  },
  { 
    cid:2,
    ccid:2,
    id: 8,
    name: 'Dell OptiPlex 9020-SFF',
    price: 299,
    description: 'This Certified Refurbished product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging. The product ships with all relevant accessories, a minimum 90-day warranty, and may arrive in a generic box. Only select sellers who maintain a high-performance bar may offer Certified Refurbished products on Amazon.com.',
    likes: 187112,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/716vsBRDp5L._AC_SL1500_.jpg',
  },
  { 
    cid:2,
    ccid:2,
    id: 9,
    name: 'Lenovo Chromebook S330 Laptop',
    price: 299,
    description: 'High performance laptop: The Chromebook S330 is equipped with a MediaTek MTK8173C Processor, Chrome OS, 4 GB LPDDR3, 64 GB emmC 5.1 and so much more',
    likes: 117812,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/61ViOMIUhmL._AC_SL1500_.jpg',
  },
  { 
    cid:2,
    ccid:2,
    name: 'Acer Nitro 5 Gaming Laptop',
    price: 299,
    description: '',
    likes: 11146342,
    rating:5,
    image:'https://images-na.ssl-images-amazon.com/images/I/71s1LRpaprL._AC_SL1500_.jpg',
  }
  
];


/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at https://angular.io/license
*/